public enum EventName
{
    Collision,
    CameraMoved,
    PlayerLaunch,
    PlayerCollision,
    Pause,
    Unpause,
    QuitGame,
    LevelCompleted,
    RestartLevel,
    PlayerFuelPickup,
    OnFire,
    Extinguish,
    Electrocuted,
    BarrelTriggered,
    BarrelExplosion,
    PlayerExploded,
    PlayerWon
}
